org: toroduque
app: guitar-chords-api
service: apollo-lambda
provider:
    name: aws
    runtime: nodejs10.x
    environment:
        MONGODB_URI: ${param:MONGODB_URI}
functions:
    graphql:
        # this is formatted as <FILENAME>.<HANDLER>
        handler: graphql.graphqlHandler
        events:
        - http:
            path: graphql
            method: post
            cors: true
        - http:
            path: graphql
            method: get
            cors: true